application: mailengine
version: dev 
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  login: admin

- url: /post
  script: main.py

- url: /build
  script: main.py
  login: admin

- url: /dispatch
  script: main.py
  login: admin

- url: /messages
  script: main.py
  login: admin

- url: /.*
  script: main.py
